@Tags(['golden'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mobile/core/theme.dart';
import 'package:mobile/features/books/contents/bloc/book_contents_bloc.dart';
import 'package:mobile/features/books/contents/bloc/book_contents_event.dart';
import 'package:mobile/features/books/contents/presentation/book_contents_screen.dart';
import 'package:mobile/features/books/data/offline_text_cache.dart';
import 'package:mobile/features/books/data/reader_font_prefs.dart';
import 'package:mobile/features/books/reader/bloc/book_reader_bloc.dart';
import 'package:mobile/features/books/reader/bloc/book_reader_event.dart';
import 'package:mobile/features/books/reader/bloc/book_reader_state.dart';
import 'package:mobile/features/books/reader/presentation/book_reader_screen.dart';

import '../support/books_harness.dart';
import '../support/fake_books_services.dart';
import '../support/figma_crosscheck.dart';

/// **Measured** geometry evidence for TAM-76 (figma-flutter Phase 2 ↔ Phase 6).
///
/// TAM-74 recorded that a full-screen side-by-side "looked basically right"
/// while three real defects were live, and that measuring the render tree caught
/// all three. So the geometry rows of this module's sweep table are produced by
/// `tester.getRect` and asserted against the Figma node bounding boxes — numbers,
/// not a glance. This test is the generator for
/// `specs/evidence/TAM-76/fidelity/render-tree/measured-geometry.md`.
///
/// Frame coordinates are quoted from Figma's 360×800 frames, whose first 52px
/// are the status bar. The screens run under `SafeArea`, which consumes that
/// inset, so a render at y=Y corresponds to a Figma y of Y+52 — applied
/// explicitly per row below rather than fudged.

const double _statusBar = 52;

/// One measured row: what Figma says vs what the render tree actually did.
class _Row {
  _Row(this.id, this.zone, this.figma, this.actual);
  final String id;
  final String zone;
  final String figma;
  final Rect actual;
  String expected = '';
  bool ok = false;
}

final List<_Row> _rows = [];

void _record(
  String id,
  String zone,
  String figma,
  Rect actual, {
  required String expected,
  required bool ok,
}) {
  _rows.add(_Row(id, zone, figma, actual)
    ..expected = expected
    ..ok = ok);
}

String _fmt(Rect r) =>
    'x=${r.left.toStringAsFixed(1)} y=${r.top.toStringAsFixed(1)} '
    '${r.width.toStringAsFixed(1)}×${r.height.toStringAsFixed(1)}';

bool _near(double a, double b, [double tol = 0.5]) => (a - b).abs() <= tol;

void main() {
  tearDownAll(() {
    final b = StringBuffer()
      ..writeln('# TAM-76 — measured render-tree geometry vs Figma')
      ..writeln()
      ..writeln('Generated by `test/goldens/books_geometry_test.dart` '
          '(`flutter test test/goldens/books_geometry_test.dart`).')
      ..writeln()
      ..writeln('Every row is `tester.getRect` on the real widget tree, compared '
          'to the node bounding box from the Phase-2 REST dump — the numeric '
          'half of the Phase-6 sweep. Figma frames include a 52px status bar '
          'that `SafeArea` consumes, so frame-y = render-y + 52 where noted.')
      ..writeln()
      ..writeln('| # | Zone | Figma (Phase 2) | Measured render | Verdict |')
      ..writeln('|---|---|---|---|---|');
    for (final r in _rows) {
      b.writeln('| ${r.id} | ${r.zone} | ${r.figma} | ${_fmt(r.actual)} | '
          '${r.ok ? 'matches' : 'DIFF'} |');
    }
    final failed = _rows.where((r) => !r.ok).length;
    b
      ..writeln()
      ..writeln('**Verdict**: ${failed == 0 ? 'PASS' : 'FAIL'} — '
          '${_rows.length - failed}/${_rows.length} zones match within 0.5px.');
    writeEvidence('TAM-76', 'render-tree/measured-geometry.md', b.toString());
  });

  testWidgets('measure: book card 120 variant (534:5505)', (tester) async {
    booksViewport(tester);
    final repo = FakeBooksRepository();
    await tester.pumpWidget(booksRouterApp(
      repository: repo,
      router: buildBooksTestRouter(repository: repo),
    ));
    await tester.pumpAndSettle();

    final card = tester.getRect(find.byKey(const ValueKey('books-card-major-1')));
    expect(_near(card.width, 120), isTrue, reason: 'card width must be 120');
    expect(_near(card.height, 206, 1), isTrue, reason: 'card height must be 206');
    _record(
      'H1',
      'Book card (carousel)',
      '534:5505 → 120×206',
      card,
      expected: '120×206',
      ok: _near(card.width, 120) && _near(card.height, 206, 1),
    );

    // Carousel gap: node 534:5475 itemSpacing = 10.
    final first = tester.getRect(find.byKey(const ValueKey('books-card-major-1')));
    final second = tester.getRect(find.byKey(const ValueKey('books-card-major-2')));
    final gap = second.left - first.right;
    expect(_near(gap, AppBooks.carouselGap), isTrue);
    _record('H2', 'Carousel item gap', '534:5475 itemSpacing = 10',
        Rect.fromLTWH(gap, 0, 0, 0),
        expected: '10', ok: _near(gap, AppBooks.carouselGap));

    // Category card: node 534:5112 → 159×100, grid gaps 10/10.
    final chalisa =
        tester.getRect(find.byKey(const ValueKey('books-category-Chalisa')));
    final aarti =
        tester.getRect(find.byKey(const ValueKey('books-category-Aarti')));
    final kavach =
        tester.getRect(find.byKey(const ValueKey('books-category-Kavach')));
    expect(_near(chalisa.width, 159, 1), isTrue);
    expect(_near(chalisa.height, 100, 1), isTrue);
    _record('H3', 'Category card', '534:5112 → 159×100 r8', chalisa,
        expected: '159×100',
        ok: _near(chalisa.width, 159, 1) && _near(chalisa.height, 100, 1));

    final colGap = aarti.left - chalisa.right;
    expect(_near(colGap, AppBooks.categoryGap), isTrue);
    _record('H4', 'Category grid column gap', '534:5111 gridColumnGap = 10',
        Rect.fromLTWH(colGap, 0, 0, 0),
        expected: '10', ok: _near(colGap, AppBooks.categoryGap));

    final rowGap = kavach.top - chalisa.bottom;
    expect(_near(rowGap, AppBooks.categoryGap), isTrue);
    _record('H5', 'Category grid row gap', '534:5111 gridRowGap = 10',
        Rect.fromLTWH(rowGap, 0, 0, 0),
        expected: '10', ok: _near(rowGap, AppBooks.categoryGap));

    // Screen edge padding: section frames pad 16 (node 534:5063).
    expect(_near(chalisa.left, AppBooks.screenPadding), isTrue);
    _record('H6', 'Screen edge padding', '534:5063 paddingLeft = 16',
        Rect.fromLTWH(chalisa.left, 0, 0, 0),
        expected: '16', ok: _near(chalisa.left, AppBooks.screenPadding));

    // Nav height: node 534:5163 = 64.
    final nav = tester.getRect(find.byKey(const ValueKey('books-home-nav')));
    expect(_near(nav.height, AppBooks.navHeight), isTrue);
    _record('H7', 'Nav height', '534:5163 → 360×64', nav,
        expected: 'h=64', ok: _near(nav.height, AppBooks.navHeight));
  });

  testWidgets('measure: contents hero + CTA + panel (639:3947)', (tester) async {
    booksViewport(tester);
    final repo = FakeBooksRepository();
    await tester.pumpWidget(booksTestApp(
      repository: repo,
      child: BlocProvider<BookContentsBloc>(
        create: (_) => BookContentsBloc(repository: repo, contentId: 'major-1')
          ..add(const BookContentsLoadRequested()),
        child: const BookContentsScreen(card: null),
      ),
    ));
    await tester.pumpAndSettle();

    // Hero cover: node 639:4019 at frame y=99 → render y = 99 − 52 = 47,
    // horizontally centred on 360 (x = 120).
    final hero = tester.getRect(find.byKey(const ValueKey('books-contents-hero')));
    final heroOk = _near(hero.top, AppBooks.contentsCardTop - _statusBar, 1) &&
        _near(hero.left, 120, 1);
    expect(heroOk, isTrue, reason: 'hero must sit at frame y=99, centred');
    _record('C1', 'Contents hero cover',
        '639:4019 → x=120 y=99(frame) 120×206', hero,
        expected: 'x=120 y=47(render)', ok: heroOk);

    // Start Reading: node 639:4105 → 95×29 at frame y=320, centred.
    final cta = tester
        .getRect(find.byKey(const ValueKey('books-contents-start-reading')));
    final ctaOk = _near(cta.top, AppBooks.contentsCtaTop - _statusBar, 1) &&
        _near(cta.height, AppBooks.contentsCtaHeight, 1) &&
        _near(cta.center.dx, 180, 1);
    expect(ctaOk, isTrue);
    _record('C2', 'Start Reading CTA',
        '639:4105 → 95×29 r8.04, y=320(frame), centred', cta,
        expected: 'h=29 y=268(render) centre x=180', ok: ctaOk);

    // Chapters panel: node 639:4029 → full-bleed from frame y=393.
    final panel =
        tester.getRect(find.byKey(const ValueKey('books-contents-list')));
    final panelOk =
        _near(panel.top, AppBooks.contentsPanelTop - _statusBar, 1) &&
            _near(panel.width, 360, 1);
    expect(panelOk, isTrue);
    _record('C3', 'Chapters panel',
        '639:4029 → 360 wide, y=393(frame), full-bleed', panel,
        expected: 'w=360 y=341(render)', ok: panelOk);

    // Kanda row: node 639:4045 → 48 tall, 20 h-padding.
    final row = tester.getRect(find.byKey(const ValueKey('books-subbook-kanda-1')));
    final rowOk = _near(row.height, AppBooks.contentsRowHeight, 1) &&
        _near(row.width, 360, 1);
    expect(rowOk, isTrue);
    _record('C4', 'Kanda row', '639:4045 → 360×48, 20h/16v pad', row,
        expected: '360×48', ok: rowOk);

    // The hero must overlap the nav — frame y=99 vs the nav's 52..116 band.
    final nav = tester.getRect(find.byKey(const ValueKey('books-contents-nav')));
    final overlaps = hero.top < nav.bottom;
    expect(overlaps, isTrue,
        reason: 'the design deliberately overlaps the cover onto the nav');
    _record('C5', 'Hero overlaps nav (paint order)',
        'cover y=99 < nav bottom 116 ⇒ ~17px overlap, cover painted after nav',
        Rect.fromLTRB(hero.top, nav.bottom, 0, 0),
        expected: 'hero.top < nav.bottom', ok: overlaps);
  });

  testWidgets('measure: reader column + CTAs (620:3904)', (tester) async {
    booksViewport(tester);
    final repo = FakeBooksRepository();
    final bloc = BookReaderBloc(
      repository: repo,
      cache: InMemoryOfflineTextCache(),
      fontPrefs: InMemoryReaderFontPrefs(),
      contentId: 'major-1',
      mode: BookReaderMode.majorBook,
      audio: FakeBookReaderAudioPort(),
      contents: fakeBookContents(),
    )..add(const BookReaderStarted());
    addTearDown(bloc.close);

    await tester.pumpWidget(booksTestApp(
      repository: repo,
      child: BlocProvider<BookReaderBloc>.value(
        value: bloc,
        child: const BookReaderScreen(bookTitle: 'Valmiki Ramayan'),
      ),
    ));
    await tester.pumpAndSettle();

    // Title: node 621:4078 → 328 wide at x=16.
    final title = tester.getRect(find.byKey(const ValueKey('books-reader-title')));
    final titleOk =
        _near(title.left, AppBooks.readerPaddingH, 1) && _near(title.width, 328, 1);
    expect(titleOk, isTrue);
    _record('R1', 'Reader chapter title', '621:4078 → 328 wide at x=16', title,
        expected: 'x=16 w=328', ok: titleOk);

    // Listen Audio: node 663:7474 → 37 tall, centred on the 360 frame.
    final listen =
        tester.getRect(find.byKey(const ValueKey('books-reader-listen')));
    final listenOk = _near(listen.height, AppBooks.buttonHeight, 1) &&
        _near(listen.center.dx, 180, 1);
    expect(listenOk, isTrue);
    _record('R2', 'Listen Audio button',
        '663:7474 → 127×37 at x=116 ⇒ centred on 360', listen,
        expected: 'h=37, centre x=180', ok: listenOk);

    // Body: node 620:4076 → 328 wide at x=16.
    final body = tester.getRect(find.byKey(const ValueKey('books-reader-body')));
    final bodyOk =
        _near(body.left, AppBooks.readerPaddingH, 1) && _near(body.width, 328, 1);
    expect(bodyOk, isTrue);
    _record('R3', 'Reader body', '620:4076 → 328 wide at x=16, 16/28', body,
        expected: 'x=16 w=328', ok: bodyOk);

    // Prev/Next: node 663:4305 → space-between across the 328 column.
    final prev =
        tester.getRect(find.byKey(const ValueKey('books-reader-previous')));
    final next = tester.getRect(find.byKey(const ValueKey('books-reader-next')));
    final prevOk = _near(prev.left, AppBooks.readerPaddingH, 1) &&
        _near(prev.height, AppBooks.buttonHeight, 1);
    final nextOk = _near(next.right, 360 - AppBooks.readerPaddingH, 1) &&
        _near(next.height, AppBooks.buttonHeight, 1);
    expect(prevOk, isTrue);
    expect(nextOk, isTrue);
    _record('R4', 'Previous button', '663:4248 → 104×37 at x=16', prev,
        expected: 'x=16 h=37', ok: prevOk);
    _record('R5', 'Next button', '663:4298 → 79×37, right edge at x=344', next,
        expected: 'right=344 h=37', ok: nextOk);

    // Nav action frames: 44 tap target (node I620:3917;5186:10379), §12.
    final fontBtn =
        tester.getRect(find.byKey(const ValueKey('books-reader-font-btn')));
    final fontOk = _near(fontBtn.width, AppBooks.navActionFrame, 1) &&
        _near(fontBtn.height, AppBooks.navActionFrame, 1);
    expect(fontOk, isTrue);
    _record('R6', 'Font-settings tap target',
        'I620:3917;5186:10379 → 44×44 (≥44, §12)', fontBtn,
        expected: '44×44', ok: fontOk);

    // Body line-height must follow the font size (28/16 = 1.75).
    final bodyStyle =
        tester.widget<Text>(find.byKey(const ValueKey('books-reader-body'))).style!;
    final lhOk = _near(bodyStyle.height! * bodyStyle.fontSize!,
        AppBooks.readerFontDefault * AppBooks.readerBodyLineRatio, 0.1);
    expect(lhOk, isTrue);
    _record('R7', 'Body line-height ratio', '620:4076 → 16/28 ⇒ ratio 1.75',
        Rect.fromLTWH(bodyStyle.height! * bodyStyle.fontSize!, 0, 0, 0),
        expected: '28.0', ok: lhOk);
  });

  testWidgets('measure: chapters drawer (637:4191)', (tester) async {
    booksViewport(tester);
    final repo = FakeBooksRepository();
    final bloc = BookReaderBloc(
      repository: repo,
      cache: InMemoryOfflineTextCache(),
      fontPrefs: InMemoryReaderFontPrefs(),
      contentId: 'major-1',
      mode: BookReaderMode.majorBook,
      audio: FakeBookReaderAudioPort(),
      contents: fakeBookContents(),
    )..add(const BookReaderStarted());
    addTearDown(bloc.close);

    await tester.pumpWidget(booksTestApp(
      repository: repo,
      child: BlocProvider<BookReaderBloc>.value(
        value: bloc,
        child: const BookReaderScreen(bookTitle: 'Valmiki Ramayan'),
      ),
    ));
    await tester.pumpAndSettle();
    bloc.add(const BookReaderDrawerToggled(open: true));
    await tester.pumpAndSettle();

    // Panel: node 637:4366 → 280 wide, right-aligned on the 360 frame.
    final list = tester.getRect(find.byKey(const ValueKey('books-drawer-list')));
    final panelOk = _near(list.width, AppBooks.drawerWidth, 1) &&
        _near(list.right, 360, 1);
    expect(panelOk, isTrue);
    _record('D1', 'Drawer panel', '637:4366 → 280 wide, right-aligned', list,
        expected: 'w=280 right=360', ok: panelOk);

    // Chapter row: node 637:4371 → 48 tall.
    final row = tester
        .getRect(find.byKey(const ValueKey('books-drawer-chapter-ch-1')));
    final rowOk = _near(row.height, AppBooks.drawerRowHeight, 1) &&
        _near(row.width, AppBooks.drawerWidth, 1);
    expect(rowOk, isTrue);
    _record('D2', 'Drawer chapter row', '637:4371 → 280×48, 20h/16v pad', row,
        expected: '280×48', ok: rowOk);

    // Header: node 637:4417 → 280×179.
    final cover = tester.getRect(find.byKey(const ValueKey('books-drawer-cover')));
    final coverOk = _near(cover.width, AppBooks.cardWidthSm, 1) &&
        _near(cover.height, 147, 1.5);
    expect(coverOk, isTrue);
    _record('D3', 'Drawer cover (sm variant)', '637:4420 → 100×147', cover,
        expected: '100×147', ok: coverOk);
  });

  testWidgets('measure: font overlay (637:4463)', (tester) async {
    booksViewport(tester);
    final repo = FakeBooksRepository();
    final bloc = BookReaderBloc(
      repository: repo,
      cache: InMemoryOfflineTextCache(),
      fontPrefs: InMemoryReaderFontPrefs(),
      contentId: 'major-1',
      mode: BookReaderMode.majorBook,
      audio: FakeBookReaderAudioPort(),
      contents: fakeBookContents(),
    )..add(const BookReaderStarted());
    addTearDown(bloc.close);

    await tester.pumpWidget(booksTestApp(
      repository: repo,
      child: BlocProvider<BookReaderBloc>.value(
        value: bloc,
        child: const BookReaderScreen(bookTitle: 'Valmiki Ramayan'),
      ),
    ));
    await tester.pumpAndSettle();
    bloc.add(const BookReaderFontOverlayToggled(open: true));
    await tester.pumpAndSettle();

    // Panel: node 620:3844 → 64 tall, drops directly below the 64px nav.
    final panel = tester.getRect(find.byKey(const ValueKey('books-font-overlay')));
    final panelOk = _near(panel.height, AppBooks.fontPanelHeight, 1) &&
        _near(panel.top, AppBooks.navHeight, 1);
    expect(panelOk, isTrue);
    _record('F1', 'Font panel', '620:3844 → 359×64, sits at the nav bottom (y=116 frame)',
        panel, expected: 'h=64, y=64(render)', ok: panelOk);

    // Value box: node 620:3861 → 51×32.
    final value = tester.getRect(find.byKey(const ValueKey('books-font-value')));
    final valueOk = _near(value.width, AppBooks.fontValueBoxWidth, 1) &&
        _near(value.height, AppBooks.fontValueBoxHeight, 1);
    expect(valueOk, isTrue);
    _record('F2', 'Font value box', '620:3861 → 51×32 r4, stroke w2', value,
        expected: '51×32', ok: valueOk);
  });
}
