@Tags(['golden'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mobile/core/theme.dart';
import 'package:mobile/features/home/data/home_models.dart';

import '../support/fake_home_services.dart';
import '../support/figma_crosscheck.dart';
import '../support/home_harness.dart';

/// **Measured** geometry evidence for TAM-62 (figma-flutter Phase 2 ↔ Phase 6).
///
/// TAM-74 recorded that a full-screen side-by-side "looked basically right"
/// while three real defects were live, and TAM-76 that only measuring/cropping
/// caught four more. Home repeated the lesson: this file's numbers caught the
/// carousel dots being centred where the node pins them bottom-RIGHT (row B4).
/// So the geometry rows of the sweep table are produced by `tester.getRect` and
/// asserted against the `285:3464` REST dump — numbers, not a glance.
///
/// Generator for `specs/evidence/TAM-62/fidelity/render-tree/measured-geometry.md`.
///
/// Home's frame is 360 wide and 3685 tall (a scrolling feed, not a 360×800
/// device frame), so rows quote node bounding boxes and the deltas BETWEEN
/// nodes rather than absolute frame-y. `SafeArea` consumes no inset here: the
/// test view has zero padding, and the Figma status bar (285:3465) is OS chrome.
class _Row {
  _Row(this.id, this.zone, this.figma, this.actual, this.expected, this.ok);
  final String id;
  final String zone;
  final String figma;
  final String actual;
  final String expected;
  final bool ok;
}

final List<_Row> _rows = [];

void _record(
  String id,
  String zone,
  String figma, {
  required String actual,
  required String expected,
  required bool ok,
}) =>
    _rows.add(_Row(id, zone, figma, actual, expected, ok));

String _fmt(Rect r) =>
    'x=${r.left.toStringAsFixed(1)} y=${r.top.toStringAsFixed(1)} '
    '${r.width.toStringAsFixed(1)}×${r.height.toStringAsFixed(1)}';

String _size(Rect r) =>
    '${r.width.toStringAsFixed(1)}×${r.height.toStringAsFixed(1)}';

bool _near(double a, double b, [double tol = 0.5]) => (a - b).abs() <= tol;

/// A feed card's CONTENT box — the outer rect less the 1px hairline (285:3539),
/// which Flutter strokes inside. Figma's equivalent is node 285:3540.
Rect _contentBox(Rect card) => card.deflate(AppHome.cardBorder);

void main() {
  tearDownAll(() {
    final failed = _rows.where((r) => !r.ok).length;
    final b = StringBuffer()
      ..writeln('# TAM-62 — measured render-tree geometry vs Figma')
      ..writeln()
      ..writeln('Generated by `test/goldens/home_geometry_test.dart` '
          '(`flutter test test/goldens/home_geometry_test.dart`).')
      ..writeln()
      ..writeln('Every row is `tester.getRect` on the real widget tree, compared '
          'to the node bounding box from the Phase-2 REST dump '
          '(`scratch/home_root.json`, node `285:3464`) — the numeric half of the '
          'Phase-6 sweep. Home\'s frame is a 360×3685 scrolling feed, so rows '
          'quote node sizes and node-to-node deltas rather than absolute frame-y.')
      ..writeln()
      ..writeln('| # | Zone | Figma (Phase 2) | Expected | Measured | Verdict |')
      ..writeln('|---|---|---|---|---|---|');
    for (final r in _rows) {
      b.writeln('| ${r.id} | ${r.zone} | ${r.figma} | ${r.expected} | '
          '${r.actual} | ${r.ok ? 'matches' : 'DIFF'} |');
    }
    b
      ..writeln()
      ..writeln('**Verdict**: ${failed == 0 ? 'PASS' : 'FAIL'} — '
          '${_rows.length - failed}/${_rows.length} zones match their node.')
      ..writeln()
      ..writeln('Tolerance is 0.5px except where the row\'s `Expected` column '
          'states otherwise and says why: hugging buttons/pills (W4/A4/B5) are '
          'within ~1.5px of the node because they size to Skia\'s Inter advance '
          'widths rather than Figma\'s text engine; the card-content rows '
          '(W1/W2/W3/A1/A2) are 358 not 360 because Flutter strokes the 285:3539 '
          'hairline INSIDE the box (W1b); the help glyph (H4) is 19.05 not 20 '
          'because Figma rounded its export canvas to viewBox 20×21.');
    writeEvidence('TAM-62', 'render-tree/measured-geometry.md', b.toString());
  });

  testWidgets('measure: header (285:3482)', (tester) async {
    await pumpHome(tester, repository: FakeHomeRepository());

    // Node 285:3482 is 108 tall = 12 pad + 40 row + 12 gap + 32 search + 12 pad.
    // Search (285:3499) is out of Phase 1 (PRD §6) ⇒ 12 + 40 + 12 = 64.
    final header = tester.getRect(find.byKey(const Key('home-header')));
    final headerOk = _near(header.height, 64) && _near(header.width, 360);
    expect(headerOk, isTrue);
    _record('H1', 'Header block', '285:3482 → 360×108 − 44 search row (PRD §6)',
        actual: _size(header), expected: '360×64', ok: headerOk);

    // Logo: node 285:3485 → 36×36, at the frame's 16 padding.
    final logo = tester.getRect(find.byKey(const Key('home-header-logo')));
    final logoOk = _near(logo.width, 36) &&
        _near(logo.height, 36) &&
        _near(logo.left, AppHome.screenPadding);
    expect(logoOk, isTrue);
    _record('H2', 'Logo mark', '285:3485 → 36×36 at x=16 (285:3482 padLeft)',
        actual: _fmt(logo), expected: '36×36 at x=16', ok: logoOk);

    // Logo → wordmark gap: node 285:3484 itemSpacing = 8.
    final wordmark =
        tester.getRect(find.byKey(const Key('home-header-wordmark')));
    final logoGap = wordmark.left - logo.right;
    final logoGapOk = _near(logoGap, AppHome.logoWordmarkGap);
    expect(logoGapOk, isTrue);
    _record('H3', 'Logo → wordmark gap', '285:3484 itemSpacing = 8',
        actual: logoGap.toStringAsFixed(2), expected: '8', ok: logoGapOk);

    // Help glyph: node 285:3495 → a 20×20 frame; its vector (285:3496) inks
    // 20×20.0033. Figma rounds the exported SVG canvas UP to viewBox="0 0 20 21",
    // and flutter_svg contain-fits that into the requested 20×20 box ⇒ 19.05×20.
    // 0.95px of width on a 20px glyph, caused by the export's canvas rounding —
    // BoxFit.fill would "fix" the width by squashing the glyph 5% vertically,
    // which is worse. Recorded, not chased (see the sweep table's note).
    final help = tester.getRect(find.byKey(const Key('home-header-help')));
    final helpOk = _near(help.width, 20, 1) && _near(help.height, 20);
    expect(helpOk, isTrue);
    _record('H4', 'Help glyph',
        '285:3495 → 20×20 frame, vector 285:3496 inks 20×20.0033',
        actual: _size(help),
        expected: '≈20×20 (19.05 wide: viewBox 20×21 contain-fitted)',
        ok: helpOk);

    // Avatar: node 285:3497 → 40×40, right edge at the frame's 16 padding.
    final avatar = tester.getRect(find.byKey(const Key('home-header-avatar')));
    final avatarOk = _near(avatar.width, 40) &&
        _near(avatar.height, 40) &&
        _near(avatar.right, 360 - AppHome.screenPadding);
    expect(avatarOk, isTrue);
    _record('H5', 'Profile avatar', '285:3497 → 40×40, right edge x=344',
        actual: _fmt(avatar), expected: '40×40, right=344', ok: avatarOk);

    // Help → avatar gap: node 285:3494 itemSpacing = 15.99.
    final trailingGap = avatar.left - help.right;
    final trailingOk = _near(trailingGap, AppHome.headerTrailingGap);
    expect(trailingOk, isTrue);
    _record('H6', 'Help → avatar gap', '285:3494 itemSpacing = 15.99',
        actual: trailingGap.toStringAsFixed(2),
        expected: '15.99',
        ok: trailingOk);
  });

  testWidgets('measure: banner carousel + dots (285:3506/3507)', (tester) async {
    await pumpHome(tester, repository: FakeHomeRepository());

    // Block: node 285:3506 → 360×178 = 12 top + 150 banner + 16 bottom.
    final block = tester.getRect(find.byKey(const Key('home-banner-carousel')));
    final blockOk = _near(block.height, 178) && _near(block.width, 360);
    expect(blockOk, isTrue);
    _record('B1', 'Banner block', '285:3506 → 360×178 (12 + 150 + 16)',
        actual: _size(block), expected: '360×178', ok: blockOk);

    // Banner: node 285:3507 → 328×150 r8 at x=16.
    final banner = tester.getRect(find.byKey(const Key('home-banner-b-module')));
    final bannerOk = _near(banner.width, AppHome.bannerWidth) &&
        _near(banner.height, AppHome.bannerHeight) &&
        _near(banner.left, AppHome.screenPadding);
    expect(bannerOk, isTrue);
    _record('B2', 'Banner', '285:3507 → 328×150 r8 at x=16',
        actual: _fmt(banner), expected: '328×150 at x=16', ok: bannerOk);

    // Dots: node I285:3507;224:1357 → 8px dots, 4 gap (32 wide for 3).
    final dots = tester.getRect(find.byKey(const Key('home-banner-dots')));
    const count = 4; // the fixture ships 4 banners
    const expectedWidth =
        count * AppHome.bannerDotSize + (count - 1) * AppHome.bannerDotGap;
    final dotsSizeOk =
        _near(dots.height, AppHome.bannerDotSize) && _near(dots.width, expectedWidth);
    expect(dotsSizeOk, isTrue);
    _record('B3', 'Carousel dots', 'I285:3507;224:1357 → 8px dots, gap 4 (32 for 3)',
        actual: _size(dots),
        expected: '${expectedWidth.toStringAsFixed(0)}×8 for 4 dots',
        ok: dotsSizeOk);

    // THE ROW THIS FILE EARNED ITS KEEP ON: the dots are pinned bottom-RIGHT
    // (right inset 16, bottom inset 16), NOT centred. Centring them — the
    // obvious carousel default, and what shipped before this sweep — put them
    // 132px left of the node.
    final rightInset = banner.right - dots.right;
    final bottomInset = banner.bottom - dots.bottom;
    final dotsPosOk = _near(rightInset, AppHome.bannerDotsRightInset) &&
        _near(bottomInset, AppHome.bannerDotsBottomInset);
    expect(dotsPosOk, isTrue,
        reason: 'dots must sit at the banner bottom-right, inset 16/16');
    _record('B4', 'Carousel dots position',
        'I285:3507;224:1357 inside 285:3507 ⇒ right inset 16, bottom inset 16',
        actual: 'right=${rightInset.toStringAsFixed(1)} '
            'bottom=${bottomInset.toStringAsFixed(1)}',
        expected: 'right=16 bottom=16',
        ok: dotsPosOk);
  });

  testWidgets('measure: shortcut grid (2569:15302 — TAM-132 3×2 layout)',
      (tester) async {
    await pumpHome(tester, repository: FakeHomeRepository());

    // Card: TAM-132 flipped to Figma frame 2569:15302 (6-tile system) — 3 cols
    // at ~103 dp wide. GridView computes the effective width from the
    // available 328 dp inner width minus 2×10 dp gaps ÷ 3 cols ≈ 102.67 dp,
    // which sits inside `_near`'s 0.5-dp tolerance around
    // `AppHome.shortcutCardWidth = 103`.
    final aarti = tester.getRect(find.byKey(const Key('home-shortcut-aarti_bhajans')));
    final mantras =
        tester.getRect(find.byKey(const Key('home-shortcut-mantras_stutis')));
    // The fake fixture ships only 4 rows in a 3-col grid → row 0 is
    // [aarti, mantras, ringtone]; row 1 starts with `set_wallpaper`.
    final wallpaper =
        tester.getRect(find.byKey(const Key('home-shortcut-set_wallpaper')));
    final cardOk = _near(aarti.width, AppHome.shortcutCardWidth) &&
        _near(aarti.height, AppHome.shortcutCardHeight);
    expect(cardOk, isTrue);
    _record('S1', 'Shortcut card', '2569:15302 → 103×117 r8 (TAM-132)',
        actual: _size(aarti), expected: '103×117', ok: cardOk);

    // Grid gaps: 10 across, 10 down.
    final colGap = mantras.left - aarti.right;
    final colOk = _near(colGap, AppHome.shortcutGap);
    expect(colOk, isTrue);
    _record('S2', 'Grid column gap', '2569:15302 → 10',
        actual: colGap.toStringAsFixed(2), expected: '10', ok: colOk);

    final rowGap = wallpaper.top - aarti.bottom;
    final rowOk = _near(rowGap, AppHome.shortcutGap);
    expect(rowOk, isTrue);
    _record('S3', 'Grid row gap', '2569:15302 → 10',
        actual: rowGap.toStringAsFixed(2), expected: '10', ok: rowOk);

    // Block padding: node 285:3508 pads 16 l/r (unchanged from TAM-62).
    final padOk = _near(aarti.left, AppHome.screenPadding) &&
        _near(mantras.right + AppHome.shortcutGap + AppHome.shortcutCardWidth,
            360 - AppHome.screenPadding, 1.5);
    expect(padOk, isTrue);
    _record('S4', 'Grid block padding', '285:3508 → padLeft/Right 16',
        actual: 'left=${aarti.left.toStringAsFixed(1)}',
        expected: 'left=16',
        ok: padOk);

    // Grid block: 328×244 (2×117 + 10 gap = 244) — 2 rows. GridView computes
    // effective card height from the constrained crossAxis width via the aspect
    // ratio, so at 3-col × 328 dp inner width the actual card height is
    // ~116.67 dp (2× + 10 gap ≈ 243.33 dp). Widen the tolerance to 1 dp to
    // accommodate the sub-pixel rounding.
    final grid = tester.getRect(find.byKey(const Key('home-shortcut-grid')));
    final gridOk = _near(wallpaper.bottom - aarti.top, 244, 1.0);
    expect(gridOk, isTrue);
    _record('S5', 'Grid block height', '2569:15302 → 2×117 + 10 = 244',
        actual: (wallpaper.bottom - aarti.top).toStringAsFixed(1),
        expected: '244',
        ok: gridOk);
    expect(grid.width, 360);
  });

  testWidgets('measure: wallpaper feed card (285:3539)', (tester) async {
    await pumpHome(
      tester,
      repository: FakeHomeRepository(
        banners: const [],
        items: [
          homeFeedItem(
            id: 'f-wallpaper',
            contentType: HomeContentType.wallpaper,
            module: 'wallpaper',
            ctaLabel: 'Set Wallpaper',
            label: 'Set Wallpaper',
            subtitle: 'Hanuman Blessing',
            badge: HomeBadge.trending,
          ),
        ],
      ),
      viewportHeight: 1600,
    );

    // Card body: node 285:3540 → 360×698 = 72 header + 574 hero + 52 footer.
    //
    // The card Container paints the 285:3539 hairline, and Flutter's
    // BoxDecoration Border always strokes INSIDE and insets its child, so the
    // measured OUTER box is 698 + 2×1 = 700 and the content box is 698. Figma's
    // stroke is `strokeAlign: CENTER` — it straddles the edge — which is why the
    // node pair reads 699 (outer, 285:3539) / 698 (content, 285:3540). Compare
    // content to content; the 1px outer delta gets its own row.
    final card = tester.getRect(find.byKey(const Key('home-feed-card-f-wallpaper')));
    final content = _contentBox(card);
    final cardOk = _near(content.width, 360, 2) && _near(content.height, 698, 1);
    expect(cardOk, isTrue);
    _record('W1', 'Wallpaper card (content)', '285:3540 → 360×698 (72 + 574 + 52)',
        actual: _size(content), expected: '≈360×698', ok: cardOk);

    // The 1px outer delta, stated rather than hidden.
    final outerOk = _near(card.height, 700, 0.5);
    expect(outerOk, isTrue);
    _record('W1b', 'Wallpaper card (outer box)',
        '285:3539 → 360×699 (stroke #B8B8B8 w1, strokeAlign CENTER)',
        actual: _size(card),
        expected: '360×700 — Flutter strokes INSIDE (+1 vs Figma\'s centred stroke)',
        ok: outerOk);

    // Header row: node 285:3541 → 360×72, 16 pad.
    final header =
        tester.getRect(find.byKey(const Key('home-feed-card-header-f-wallpaper')));
    final headerOk = _near(header.height, AppHome.headerBlockHeight) &&
        _near(header.width, 360, 2);
    expect(headerOk, isTrue);
    _record('W2', 'Card header row', '285:3541 → 360×72, 16 pad',
        actual: _size(header),
        expected: '≈360×72 (358 wide inside the hairline)',
        ok: headerOk);

    // Hero: node 285:3555 → 360×574 (the 9:16-ish preview). Width is 358 = 360
    // less the inside-stroked hairline (see W1b).
    final hero = tester.getRect(find.byKey(const Key('home-feed-hero-f-wallpaper')));
    final heroOk =
        _near(hero.height, AppHome.heroHeight) && _near(hero.width, 360, 2);
    expect(heroOk, isTrue);
    _record('W3', 'Hero preview', '285:3555 → 360×574',
        actual: _size(hero), expected: '≈360×574 (358 wide inside the hairline)',
        ok: heroOk);

    // CTA: node 285:3557 → 112×36 r8, hugging its label, centred, 20 above the
    // hero's bottom edge (hero bottom 20560 − CTA bottom 20528 = 32... the node
    // sits at y=20492..20528 and the hero ends at 20560 ⇒ 32 gap). The button
    // HUGS, so width is Skia's Inter advance for "Set Wallpaper" + 2×12 pad.
    final cta = tester.getRect(find.byKey(const Key('home-feed-cta-f-wallpaper')));
    final ctaOk = _near(cta.height, AppHome.ctaHeight) &&
        _near(cta.center.dx, 180, 1) &&
        _near(cta.width, 112, 6);
    expect(ctaOk, isTrue,
        reason: 'CTA must be 36 tall, centred, ~112 wide (hugs its label)');
    _record('W4', 'Hero CTA (Main Buttons)',
        '285:3557 → 112×36 r8, hugs label, 8/12 pad, centred',
        actual: _fmt(cta),
        expected: 'h=36, centre x=180, w≈112',
        ok: ctaOk);

    // Engagement footer: node 285:3559 → 328×24, 8 h-pad inside 285:3558.
    // 285:3559 spans x=−22925..−22597 (16 from the frame edge) with padLeft/Right
    // 8 ⇒ content inset 24 from each edge of the card's content box.
    final like = tester.getRect(find.byKey(const Key('home-feed-like-f-wallpaper')));
    final share =
        tester.getRect(find.byKey(const Key('home-feed-share-f-wallpaper')));
    final likeInset = like.left - content.left;
    final shareInset = content.right - share.right;
    final footerOk = _near(likeInset, 24) && _near(shareInset, 24, 1);
    expect(footerOk, isTrue);
    _record('W5', 'Engagement footer span',
        '285:3559 → 328×24 at x=16, pad 8 ⇒ 24 inset each side',
        actual: 'left inset=${likeInset.toStringAsFixed(1)} '
            'right inset=${shareInset.toStringAsFixed(1)}',
        expected: '24 / 24',
        ok: footerOk);

    // SPACE_BETWEEN: nodes 285:3560/3565/3570 sit at x=−22917 / −22791.78 /
    // −22664.72 ⇒ two equal 76.89 gaps across the 312 content width.
    final view = tester.getRect(find.byKey(const Key('home-feed-view-f-wallpaper')));
    final gap1 = view.left - like.right;
    final gap2 = share.left - view.left - view.width;
    final gapsOk = _near(gap1, gap2, 1);
    expect(gapsOk, isTrue, reason: 'footer must be SPACE_BETWEEN (equal gaps)');
    _record('W6', 'Footer SPACE_BETWEEN',
        '285:3559 primaryAxisAlignItems=SPACE_BETWEEN ⇒ equal gaps (76.89 in the mock)',
        actual: 'gap1=${gap1.toStringAsFixed(1)} gap2=${gap2.toStringAsFixed(1)}',
        expected: 'gap1 == gap2',
        ok: gapsOk);

    // Badge pill: node 285:3552 glyph → 14×14; the pill's Background (285:3551)
    // has fills:[] visible:false ⇒ NO chip, just glyph + label.
    final badge = tester.getRect(find.byKey(const Key('home-feed-badge-f-wallpaper')));
    final badgeOk = _near(badge.height, 16, 1);
    expect(badgeOk, isTrue);
    _record('B5', 'Badge pill', '285:3551 → 76×16, fill visible:false (no chip)',
        actual: _size(badge), expected: 'h=16', ok: badgeOk);
  });

  testWidgets('measure: audio feed card + mini player (285:3639)', (tester) async {
    await pumpHome(
      tester,
      repository: FakeHomeRepository(
        banners: const [],
        items: [
          homeFeedItem(
            id: 'f-aarti',
            contentType: HomeContentType.aarti,
            module: 'aarti',
            ctaLabel: 'Listen to more',
            label: 'Aarti & Bhajan',
            subtitle: 'Hanuman Chalisa',
            badge: HomeBadge.suggested,
            audioPreviewUrl: 'https://cdn.example.com/aarti.mp3',
          ),
        ],
      ),
      viewportHeight: 1000,
    );

    // Card: node 285:3639 → 360×484 = 72 header + 360 audio + 52 footer.
    // Content box vs outer box: same 1px hairline story as W1/W1b.
    final card = tester.getRect(find.byKey(const Key('home-feed-card-f-aarti')));
    final content = _contentBox(card);
    final cardOk =
        _near(content.width, 360, 2) && _near(content.height, 484, 1);
    expect(cardOk, isTrue);
    _record('A1', 'Audio card (content)', '285:3639 → 360×484 (72 + 360 + 52)',
        actual: _size(content), expected: '≈360×484', ok: cardOk);

    // Audio preview area: node 285:3655 → 360×360, square.
    final audio = tester.getRect(find.byKey(const Key('home-feed-audio-f-aarti')));
    final audioOk = _near(audio.height, AppHome.audioAreaHeight) &&
        _near(audio.width, 360, 2);
    expect(audioOk, isTrue);
    _record('A2', 'Audio preview area', '285:3655 → 360×360 #FCDBD3',
        actual: _size(audio), expected: '≈360×360', ok: audioOk);

    // Play/pause: node 285:3668 → 48×48, at the mini player's 16 pad.
    final toggle =
        tester.getRect(find.byKey(const Key('home-feed-audio-toggle-f-aarti')));
    final toggleInset = toggle.left - content.left;
    final toggleOk = _near(toggle.width, AppHome.playButtonSize) &&
        _near(toggle.height, AppHome.playButtonSize) &&
        _near(toggleInset, AppHome.miniPlayerPadding);
    expect(toggleOk, isTrue);
    _record('A3', 'Play/Pause button', '285:3668 → 48×48 r12, 16 from the edge',
        actual: '${_size(toggle)} at inset ${toggleInset.toStringAsFixed(1)}',
        expected: '48×48 at inset 16',
        ok: toggleOk);

    // Audio CTA: node 285:3672 → 98×28 r8, right edge at the 16 pad, hugging.
    final cta = tester.getRect(find.byKey(const Key('home-feed-cta-f-aarti')));
    final ctaInset = content.right - cta.right;
    final ctaOk = _near(cta.height, AppHome.ctaAudioHeight) &&
        _near(ctaInset, AppHome.miniPlayerPadding) &&
        _near(cta.width, 98, 6);
    expect(ctaOk, isTrue);
    _record('A4', 'Audio CTA (Main Buttons)',
        '285:3672 → 98×28 r8, hugs label, 6/10 pad, 16 from the edge',
        actual: '${_size(cta)} at right inset ${ctaInset.toStringAsFixed(1)}',
        expected: 'h=28, right inset 16, w≈98',
        ok: ctaOk);

    // Controls row: node 285:3667 → SPACE_BETWEEN across 328.
    final controlsOk = _near(toggleInset, AppHome.miniPlayerPadding) &&
        _near(ctaInset, AppHome.miniPlayerPadding);
    expect(controlsOk, isTrue);
    _record('A5', 'Controls row', '285:3667 → 328×48 SPACE_BETWEEN',
        actual: 'toggle inset=${toggleInset.toStringAsFixed(1)} '
            'cta inset=${ctaInset.toStringAsFixed(1)}',
        expected: 'both 16 (pinned to opposite edges)',
        ok: controlsOk);
  });
}
