-- GENERATED by apps/events/db/migrate.ts — do not edit by hand.
-- Current schema as applied by migrations/ (CI verifies this file matches a fresh apply).

CREATE TABLE events
(
    `insert_id` String,
    `event_type` LowCardinality(String),
    `user_id` String DEFAULT '',
    `device_id` String DEFAULT '',
    `pseudo_id` String DEFAULT '',
    `session_id` Int64 DEFAULT -1,
    `event_seq_id` UInt64 DEFAULT 0,
    `event_time` DateTime64(3),
    `server_time` DateTime64(3),
    `client_upload_time` DateTime64(3) DEFAULT 0,
    `event_properties` JSON DEFAULT '{}',
    `user_properties` JSON DEFAULT '{}',
    `group_properties` JSON DEFAULT '{}',
    `groups` Map(LowCardinality(String), String),
    `platform` LowCardinality(String) DEFAULT '',
    `os_name` LowCardinality(String) DEFAULT '',
    `os_version` LowCardinality(String) DEFAULT '',
    `app_version` LowCardinality(String) DEFAULT '',
    `device_brand` LowCardinality(String) DEFAULT '',
    `device_model` String DEFAULT '',
    `device_manufacturer` LowCardinality(String) DEFAULT '',
    `carrier` LowCardinality(String) DEFAULT '',
    `country` LowCardinality(String) DEFAULT '',
    `language` LowCardinality(String) DEFAULT '',
    `adid` String DEFAULT '',
    `library` LowCardinality(String) DEFAULT '',
    `ip` String DEFAULT '',
    `attempts` UInt16 DEFAULT 0,
    `retry_count` UInt16 DEFAULT 0,
    `req_guid` String DEFAULT '',
    `corrected_time` DateTime64(3) MATERIALIZED fromUnixTimestamp64Milli(multiIf(toUnixTimestamp64Milli(client_upload_time) = 0, toUnixTimestamp64Milli(event_time), toUnixTimestamp64Milli(client_upload_time) < toUnixTimestamp64Milli(event_time), toUnixTimestamp64Milli(event_time), toUnixTimestamp64Milli(server_time) - (toUnixTimestamp64Milli(client_upload_time) - toUnixTimestamp64Milli(event_time)))),
    `event_date` Date MATERIALIZED toDate(corrected_time, 'Asia/Kolkata'),
    `synthetic_sequence_time` UInt64 MATERIALIZED (toUInt64(toUnixTimestamp64Milli(corrected_time)) * 1000000) + (event_seq_id % 1000000),
    PROJECTION sessions_projection
    (
        SELECT *
        ORDER BY 
            user_id,
            session_id,
            event_time
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(server_time, 'Asia/Kolkata')
ORDER BY (event_date, event_type, user_id)
SETTINGS index_granularity = 8192;
